### ---------------------
@baseUrl = http://localhost:3000

### Solicitud para obtener un token
POST {{baseUrl}}/jwt/login/
Content-Type: application/json

{
  "email": "caebar@gmail.com",
  "password_hash": "$2b$10$NRlX6rmL6blXK9vRi8wUHu7Q7jZPWLOGqE8o6uGKokVs/c.pBrf7W",
  "id_rol": 4
}